version: "3.8"

services:
  app:
    build: .
    container_name: faq_app
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: faq_mongo
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: faq_redis
    restart: always
    ports:
      - "6379:6379"
